In [1]:
import pandas as pd 
import numpy as np

In [2]:
print("Carregando o arquivo")

df = pd.read_csv("customer_shopping_data.csv", sep=",")

Carregando o arquivo

# Exploração

###### Funções como .sample().info().discribe() e duplicate() ajudam a ter uma visão geral dos dados

In [3]:
# Recolendo amostra
df.sample(10)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
51592,I453530,C756238,Female,18,Cosmetics,5,203.30,Credit Card,4/2/2022,Mall of Istanbul
93231,I314065,C153598,Male,27,Cosmetics,5,203.30,Credit Card,12/3/2022,Istinye Park
83578,I258717,C588699,Female,48,Books,5,75.75,Debit Card,23/09/2021,Zorlu Center
15793,I111785,C156790,Female,61,Shoes,5,3000.85,Credit Card,26/04/2022,Metropol AVM
53138,I759161,C715927,Male,21,Clothing,5,1500.40,Cash,6/3/2023,Kanyon
18734,I202702,C255460,Male,59,Toys,5,179.20,Credit Card,9/11/2022,Kanyon
67655,I190334,C153861,Female,42,Food & Beverage,3,15.69,Cash,31/08/2021,Metropol AVM
14052,I167519,C239570,Female,37,Clothing,2,600.16,Credit Card,20/10/2022,Viaport Outlet
62420,I179281,C193149,Male,20,Clothing,4,1200.32,Credit Card,27/05/2022,Mall of Istanbul
35194,I129210,C194879,Male,58,Cosmetics,1,40.66,Debit Card,19/02/2023,Istinye Park

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  str
 1   customer_id     99457 non-null  str
 2   gender          99457 non-null  str
 3   age             99457 non-null  int64
 4   category        99457 non-null  str
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  str
 8   invoice_date    99457 non-null  str
 9   shopping_mall   99457 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 7.6 MB

#### Linhas duplicadas

In [5]:
df.duplicated().sum()

np.int64(0)

# Polimento

In [6]:
df[["price"]] = df[["price"]].replace("[^0-9.]","", regex=True,).astype(float)

###### colunas com inconsistências

In [7]:
print(df["shopping_mall"].unique())

<StringArray>
[           'Kanyon',    'Forum Istanbul',         'Metrocity',
      'Metropol AVM',      'Istinye Park',  'Mall of Istanbul',
 'Emaar Square Mall',       'Cevahir AVM',    'Viaport Outlet',
      'Zorlu Center']
Length: 10, dtype: str

In [8]:
df["shopping_mall"] = df["shopping_mall"].str.lower()

ajustar = {
'kanyon': 'Kanyon',
'forum istanbul': 'Forum Istanbul' ,
'metrocity avm': 'Metrocity AVM',
'metropol avm' : 'Metropol İstanbul', 
'istinye park' :  'Istinye Park',
'mall of istanbul': 'Mall of Istanbul',
'emaar square mall' : 'Emaar Square Mall',
'cevahir avm' : 'Cevahir Shopping',
'viaport outlet' : 'Viaport Outlet',
'zorlu center' : 'Zorlu Center' 
}

df["shopping_mall"] = df["shopping_mall"].replace(ajustar)

In [9]:
print(df["shopping_mall"].unique())

<StringArray>
[           'Kanyon',    'Forum Istanbul',         'metrocity',
 'Metropol İstanbul',      'Istinye Park',  'Mall of Istanbul',
 'Emaar Square Mall',  'Cevahir Shopping',    'Viaport Outlet',
      'Zorlu Center']
Length: 10, dtype: str

In [10]:
df["shopping_mall"] = df["shopping_mall"].str.capitalize()

In [11]:
print(df['shopping_mall'].unique())

<StringArray>
[            'Kanyon',     'Forum istanbul',          'Metrocity',
 'Metropol i̇stanbul',       'Istinye park',   'Mall of istanbul',
  'Emaar square mall',   'Cevahir shopping',     'Viaport outlet',
       'Zorlu center']
Length: 10, dtype: str

###### ajustando formato de datas

In [12]:
df["invoice_date"] = pd.to_datetime(df["invoice_date"], format= "mixed", dayfirst = True)

###### Utilizando o 'pd.to_datetime' para a correção de formatação de data da coluna invoice_date

In [13]:
df.head(10)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol i̇stanbul
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,2022-05-24,Forum istanbul
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,2022-03-13,Istinye park
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,2021-01-13,Mall of istanbul
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,2021-11-04,Metrocity
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,2021-08-22,Kanyon

# Anomalías

###### Localizar os valores ausentes com 2 casas decimais de ordem decrescente

In [16]:
(df.isnull().sum()*100/df.index.size).round(2).sort_values(ascending=False)

invoice_no        0.0
customer_id       0.0
gender            0.0
age               0.0
category          0.0
quantity          0.0
price             0.0
payment_method    0.0
invoice_date      0.0
shopping_mall     0.0
dtype: float64

# Finalização

###### criação do novo arquivo limpo

In [18]:
df_limpo = df.to_csv("customer_shopping_data_limpo.csv", index=False)

In [22]:
df_limpo = pd.read_csv("customer_shopping_data_limpo.csv", sep=",")

In [23]:
df_limpo.head(10)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol i̇stanbul
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,2022-05-24,Forum istanbul
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,2022-03-13,Istinye park
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,2021-01-13,Mall of istanbul
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,2021-11-04,Metrocity
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,2021-08-22,Kanyon